config/routes.rb
Rails.application.routes.draw do
  
  resources :books
  root 'homes#top'
  # get '/books' => 'books#index' 
  # post '/books' => 'books#create'
  # get 'books/:id' => 'books#show'
  
  # get 'books/:id/edit' => 'books#edit'

  # patch 'books/:id' => 'books#update'
  # delete 'books/:id' => 'books#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end
  
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def create
   @book = Book.new(book_params)
      if @book.save
        redirect_to book_path(@book), notice: 'Book was successfully created.' 
      else
        @books = Book.all
        render :index
      end
  end
  
  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
       redirect_to book_path(@book), notice: 'Book was successfully updated.'
     else
       render :edit
     end
  end
  
  def destroy
    @book = Book.find(params[:id])  
    @book.destroy  
      redirect_to books_path, notice: 'Book was successfully destroyed.' 
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
    
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li class="error_message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@book, url:book_path(@book), local:true do |f| %>
  <div class="field">
  <label>Title</label>
  <%= f.text_field :title %>
  </div>
  <div class="field">
  <label>Body</label>
  <%= f.text_area :body %>
  </div>
  <div class="action">
  <%= f.submit 'Update Book' %>
  </div>
<% end %>
</body>

<%= link_to "Show", book_path(@book) %>
|
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<body>  
  
 <h1>Books</h1>
 
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  
  <h2>New Book</h2>
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li class="error_message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @book, url:books_path, local:true do |f| %>
  <div class="field">
  <label>Title</label>
  <%= f.text_field :title %>
  </div>
  <div class="field">
  <label>Body</label>
  <%= f.text_area :body %>
  </div>
  <div class="action">
  <%= f.submit 'Create Book' %>
  </div>
<% end %>
</body>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>Title:</strong><%=@book.title %></p>
<p><strong>Body:</strong><%=@book.body %></p>

<%= link_to "Edit", edit_book_path(@book) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<html>
    <head>
        
    </head>
    
    <body>
        <h1>ようこそ<strong>Bookers</strong> へ！</h1>
        <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
        <p>印象を共有し交換することができます</p>
        <p><a href="/books">start</a></p>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>